# https://taskfile.dev
version: '3'

tasks:
  dev:
    desc: Start development.
    aliases: [ default ]
    cmds:
      - dotnet watch run --project src/DomeGym.Api/

  run:
    desc: Run the project.
    cmds:
      - dotnet run --project src/DomeGym.Api/

  restore:
    desc: Install dependencies (mostly used after cloning/pulling).
    cmds:
      - dotnet restore DomeGym.slnx

  test:
    desc: Run tests.
    cmds:
      - dotnet test
